### PR TITLE
*: make the sdk happen

### PR DESCRIPTION
**Pull request by null8626**
After more than two years of being empty, i thought it would be better for me to maintain the official Rust SDK for the Top.gg API instead!

Feel free to let me know for any feedback, thanks!

### CODE REVIEW

**Comment by pixxies** [comment]
Hey!

At last! 😊

Thanks for your contribution.

There are a few issues that break our TOS though. It seems your code scrapes our website data instead of being a wrapper for our API (which is what these SDKs are supposed to do).

Please update your code to only interact with the data available outlined in the documentation at [https://docs.top.gg](https://docs.top.gg) before we can merge and release.

Thanks for helping out! 😊

**Comment by null8626** [comment]
Scraping? i don't see any scraping here... every method uses the official Top.gg API endpoints as noted by the documentation and other top.gg SDKs

**Comment by pixxies** [comment]
April Fool's! 😅 (ok sorry)

**Comment by null8626** [comment]
it's alright, thank you so much! <3

**Pull request merged**
