### PR TITLE
*: version 1.0

### PR DESCRIPTION
**Pull request by null8626**
The following pull request does the following:
- Adds proper documentation for every function and data structure
- Adds autopost support!
- Adds error handling for 403 (forbidden) status code.
- Temporarily removes dependabot (until i become a member - i'm sure you wouldn't want dependabot knocking on your door every saturday!)
- Un-inlined several functions to improve performance

### CODE REVIEW

**Comment by null8626** [comment]
cc @pixxies

**Comment by pixxies** [comment]
Is this ready to merge or will  there be more changes? Please only open PRs when there are a batch of updates to add. If I had merged this in when you originally pinged me this would have ended up being multiple PRs.

**Review by pixxies — CHANGES_REQUESTED** [review]
"Discord" and "Top.gg" should be capitalized everywhere in the docs

**Comment by null8626** [comment]
> "Discord" and "Top.gg" should be capitalized everywhere in the docs

This should be fixed in [this commit](https://github.com/top-gg/rust-sdk/pull/4/commits/6578ebe76fb6623f49eebcb58bcaa45091d84171). Sorry, i didn't notice that review!

**Comment by ItsNeil17** [comment]
This is gonna be 1 big PR

**Comment by null8626** [comment]
> This is gonna be 1 big PR

yes because mac is slow - so i was like why not just publish v1.0 already :^)

**Comment by null8626** [comment]
okay, i think i'm done now! the project is in LGTM state now :)

**Comment by null8626** [comment]
(the library is 100% guaranteed to compile, don't worry.)

**Comment by Luke-6723** [comment]
Lets play, how old will this PR get before it gets merged

**Comment by IThundxr** [comment]
> Lets play, how old will this PR get before it gets merged

i guess a week!

**Comment by ItsNeil17** [comment]
merged nice

**Comment by null8626** [comment]
> merged nice

#9 is not yet merged, so not so nice

**Pull request merged**
