### PR TITLE
fix: fix #6

### LINKED ISSUE #6: HTTP/1.0 is deprecated
Great job with this repo, looks amazing. Only one thing stood out to me, that it's not using HTTP/1.1 which every non http-2 client should be using instead of 1.0 that's been deprecated for like a decade

https://github.com/top-gg/rust-sdk/blob/27de52628e6c7c1890be84fccac734f7451040f9/src/http.rs#L46

### PR DESCRIPTION
**Pull request by null8626**
The following pull request fixes #6.

### CODE REVIEW

**Comment by pixxies** [comment]
NANI OwO

Please save us time and only open PRs when you have a batch of fixes to push! 🙏

Ty ❤️

**Comment by null8626** [comment]
No problem! Sorry if i've ever bothered you with Discord pings/GitHub pull requests 😄

**Comment by pixxies** [comment]
It doesn't bother me it's just merging four PRs in a week will cost me more time than merging one

**Comment by null8626** [comment]
i see... noted!

**Pull request merged**
